# Generated by Django 4.1.2 on 2022-12-14 15:41
import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
