# Generated by Django 4.1.3 on 2022-12-15 10:41

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, 
                editable=False, primary_key=True, serialize=False)),
                ('post_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, 
                editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
