# Generated by Django 4.1.3 on 2022-12-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='user_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
