# Generated by Django 4.1.3 on 2022-12-15 21:49

import uuid
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rename_user_id_place_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4, 
                    editable=False, primary_key=True, 
                    serialize=False)),
                ('post_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=6, max_digits=6)),
            ],
        ),
    ]
