# Generated by Django 4.1.3 on 2022-12-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unreveal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='user_id',
            new_name='username',
        ),
    ]
