# Generated by Django 4.1.3 on 2022-12-16 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unreveal', '0003_errorresponse_successresponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4,
                                   editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4,
                                   editable=False, primary_key=True, serialize=False),
        ),
    ]
