# Generated by Django 4.1.3 on 2022-12-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unreveal', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
